### ISSUE TITLE
MC 1.21

### ISSUE THREAD

**Issue by Ludovix2812** [MiniPlaceholders/MiniPlaceholders#214] opened 2024-07-26 12:16 UTC
When i try to use the plugin for Minecraft 1.21 (using a purpur server), even if it says on modrinth that it is updated for 1.21, the console gives an error "is it up to date?" and proceeds to disable it.

**Comment by 4drian3d** [comment] 2024-07-26 22:45
duplicate of #208

**Closed by 4drian3d** 2024-07-26 22:45 UTC
